### ISSUE TITLE
Generate training and validation set for binary classification

### ISSUE THREAD

**Issue by sagarscbb** [kuixu/PrismNet#1]
NameError: name 'icshapes' is not defined

Dear Developer, 
 Please let me know, why is this error keep popping after i run the shell script you provided at this git page. What does "icshapes" defines? 

shell script: tools/gdata_bin.sh

**Comment by kuixu** [comment]
Dear @sagarscbb, Thanks for your feedback, we have fixed this problem as you mentioned. You could check out the latest code by `git pull`.

**Comment by ojziff** [comment]
Dear @kuixu,

Running `tools/gdata_bin.sh` is giving me an index out of range error as it loops through each RBP:

```
ZNF622_K562
Traceback (most recent call last):
  File "tools/generate_dataset.py", line 52, in <module>
    structs = structs[i].split(',')
IndexError: list index out of range
ZNF800_K562
Traceback (most recent call last):
  File "tools/generate_dataset.py", line 52, in <module>
    structs = structs[i].split(',')
IndexError: list index out of range
ZRANB2_K562
Traceback (most recent call last):
  File "tools/generate_dataset.py", line 52, in <module>
    structs = structs[i].split(',')
IndexError: list index out of range
```

Do you know why this is and how i can fix it?

Many thanks, Oliver

**Comment by kuixu** [comment]
@ojziff Fixed, you could check out the latest code by `git pull`. Thanks.

**Comment by ojziff** [comment]
Thanks @kuixu - that fixed it. 

However, i am now getting an error with training all the proteins models with `exp/prismnet/train_all.sh` as it cant find the log files:

```
(mypython3.6) [ziffo@int001 PrismNet]$ exp/prismnet/train_all.sh
360002
360003
AGO_HEK293 ===
ALKBH5_HEK293 ===
exp/prismnet/train_all.sh: line 28: exp/prismnet/out/log/AGO_HEK293_PrismNet_pu.log: No such file or directory
exp/prismnet/train_all.sh: line 28: exp/prismnet/out/log/ALKBH5_HEK293_PrismNet_pu.log: No such file or directory
360009
ATXN2_HEK293T ===
360010
AUH_K562 ===
exp/prismnet/train_all.sh: line 28: exp/prismnet/out/log/ATXN2_HEK293T_PrismNet_pu.log: No such file or directory
exp/prismnet/train_all.sh: line 28: exp/prismnet/out/log/AUH_K562_PrismNet_pu.log: No such file or directory
360016
360017
BCCIP_HepG2 ===
C17ORF85_HEK293 ===
exp/prismnet/train_all.sh: line 28: exp/prismnet/out/log/BCCIP_HepG2_PrismNet_pu.log: No such file or directory
exp/prismnet/train_all.sh: line 28: exp/prismnet/out/log/C17ORF85_HEK293_PrismNet_pu.log: No such file or directory
...
```

I cant find these log files in any directory. There is only the h5 and tsv files in `PrismNet/data/clip_data`.

Many thanks for your help with this!
Oliver

**Comment by kuixu** [comment]
@ojziff I have updated the code for making `out/log` firstly.

```
if [ ! -d $work_path/out ];then    
    mkdir $work_path/out
    mkdir $work_path/out/log
fi
```
